version: '3'

services:
  app:
    build:
      context: .
      target: dev
    env_file:
      - ./.envs/local/app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: ["./wait-for-it.sh", "mysql:3306", "--", "/go/bin/server"]
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.27
    container_name: mysql8
    ports:
      - "3306:3306"
    env_file:
      - ./.envs/local/mysql
    command: mysqld --authentication_policy=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
